/* =========================================================
   Data produk dan toko
   Data ini menggantikan database karena project 100% front end
   Silakan ganti isi data sesuai hasil observasi Pasar Matawai
   ========================================================= */

const products = [
  {
    id: 1,
    name: "Beras",
    category: "Sembako",
    store: "Toko Musafir Indah",
    price: 65000,
    image: "img/beras.jpeg",
    description: "Harganya 65.000/5kg. Merek beras ini yaitu SPHP, Impari, Ciherang.",
    stock: "Tersedia",
    labels: ["Buatan lokal"],
    whatsapp: "6282235751275",
    featured: true
  },
  {
    id: 2,
    name: "Gula Pasir",
    category: "Sembako",
    store: "Kios Farah",
    price: 18000,
    image: "img/gula.jpeg",
    description: "Harganya 18.000/kg. Gula pasir berkualitas tinggi dengan tekstur kristal yang bersih, putih, dan mudah larut.",
    stock: "Tersedia",
    labels: ["Siap ambil"],
    whatsapp: "6285253579182",
    featured: false
  },
  {
    id: 3,
    name: "Telur Ayam",
    category: "Sembako",
    store: "Toko Mama Isul",
    price: 68000,
    image: "img/telur.jpeg",
    description: "Harganya 68.000/pan. Telur ayam segar berkualitas dengan kandungan nutrisi yang baik dan rasa yang lezat.",
    stock: "Tersedia",
    labels: ["Siap ambil"],
    whatsapp: "6281234567890",
    featured: true
  },
  {
    id: 4,
    name: "Kopi Biji",
    category: "Sembako",
    store: "Toko Musafir Indah",
    price: 80000,
    image: "img/kopi.jpeg",
    description: "Harganya 80.000/kg. Biji kopi berkualitas dengan aroma khas dan cita rasa yang kaya.",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    whatsapp: "6282235751275",
    featured: true
  },
  {
    id: 5,
    name: "Minyak Goreng Bimoli",
    category: "Sembako",
    store: "Kios Farah",
    price: 25000,
    image: "img/bimoli.jpeg",
    description: "Harganya 25.000/liter. Minyak goreng berkualitas dari kelapa sawit pilihan yang jernih dan higienis.",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    whatsapp: "6285253579182",
    featured: false
  },
  {
    id: 6,
    name: "Sajiku",
    category: "Sembako",
    store: "Kios Farah",
    price: 7000,
    image: "img/sajiku.jpeg",
    description: "Harganya 7.000 yang kecil, yang besar 28.000. Tepung bumbu praktis dengan rempah pilihan yang menghasilkan gorengan renyah dan gurih. ",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    modes: ["Murah", "Cepat"],
    whatsapp: "6285253579182",
    featured: true
  },
  {
    id: 7,
    name: "Sabun daia",
    category: "Sembako",
    store: "Warung Nus",
    price: 5000,
    image: "img/daia.jpeg",
    description: "Harganya 23.000/kg. Deterjen berkualitas dengan formula pembersih yang efektif dan aroma segar tahan lama, membantu menjaga pakaian tetap bersih, harum, dan nyaman digunakan setiap hari.",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    whatsapp: "6281245634267",
    featured: false
  },
  {
    id: 8,
    name: "ketumbar",
    category: "Sembako",
    store: "Toko Musafir Indah",  
    price: 5000,
    image: "img/merica.jpeg",
    description: "Harganya 5.000/bungkus. Rempah berkualitas dengan aroma khas dan cita rasa yang kaya, cocok untuk berbagai masakan dan membantu menghasilkan hidangan yang lebih lezat",
    stock: "Tersedia",
    labels: ["Siap ambil"],
    whatsapp: "6282235751275",
    featured: false
  },
  {
    id: 9,
    name: "Terong",
    category: "Sayur-sayuran",
    store: "lapak Irwan",
    price: 10000,
    image: "img/terong.jpeg",
    description: "Harganya 10.000/7 buah. Sayuran berkualitas dengan tekstur lembut dan rasa khas, cocok untuk berbagai olahan masakan sehari-hari. Segar, bernutrisi, dan siap melengkapi hidangan keluarga.",
    stock: "Tersedia",
    labels: ["Bibit lokal"],
    whatsapp: "6281338864650",
    featured: true
  },
  {
    id: 10,
    name: "Tomat",
    category: "Sayur-sayuran",
    store: "Lapak Irwan",
    price: 20000,
    image: "img/tomat.jpeg",
    description: "Harganya 20.000/kg. Tomat berkualitas dengan rasa segar dan kandungan nutrisi yang baik, cocok untuk berbagai olahan masakan",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    whatsapp: "6281338864650",
    featured: false
  },
  {
    id: 11,
    name: "Wortel",
    category: "Sayur-sayuran",
    store: "Lapak febriano",
    price: 30000,
    image: "img/wortel.jpeg",
    description: "Harganya 30.000/kg. Sayuran berkualitas dengan tekstur renyah dan rasa manis alami, kaya akan vitamin",
    stock: "Tersedia",
    labels: ["Harga hemat"],
    whatsapp: "6282210854706",
    featured: false
  },
  {
    id: 12,
    name: "Kentang",
    category: "Sayur-sayuran",
    store: "Lapak febriano",
    price: 20000,
    image: "img/kentang.jpeg",
    description: "Harganya 20.000/kg. Umbi berkualitas dengan tekstur padat dan rasa alami, cocok untuk berbagai olahan masakan sehari-hari.",
    stock: "Tersedia",
    labels: ["Bibit Lokal"],
    whatsapp: "6282210854706",
    featured: true
  },
  {
    id: 13,
    name: "Cabe Keriting",
    category: "Sayur-sayuran",
    store: "Lapak febriano",
    price: 70000,
    image: "img/cabe keriting.jpeg",
    description: "Harganya 70.000/kg. Cabai berkualitas dengan rasa pedas khas dan warna merah cerah, cocok untuk berbagai masakan dan sambal.",
    stock: "Tersedia",
    labels: ["Bibit Lokal"],
    whatsapp: "6282210854706",
    featured: true
  },
  {
    id: 14,
    name: "Buncis",
    category: "Sayur-sayuran",
    store: "Lapak febriano",
    price: 25000,
    image: "img/buncis.jpeg",
    description: "Harganya 25.000/kg. Sayuran berkualitas dengan tekstur renyah dan rasa alami yang lezat, cocok untuk berbagai olahan masakan sehari-hari serta kaya akan serat dan nutrisi yang baik untuk kesehatan.",
    stock: "Tersedia",
    labels: ["Bibit Lokal"],
    whatsapp: "6282210854706",
    featured: true
  },
  {
    id: 15,
    name: "Ikan basah",
    category: "Daging",
    store: "Lapak Andi",
    price: 100000,
    image: "img/ikan basah.jpeg",
    description: "Harganya 100.000/kumpul. Disini jual berbagai jenis ikan yaitu ikan Tongkol, Tembang, Kombong",
    stock: "Tersedia",
    labels: ["Ikan Segar"],
    whatsapp: "6282567987345",
    featured: true
  },
  {
    id: 16,
    name: "Ikan Kering",
    category: "Daging",
    store: "Lapak Mas Wahyu",
    price: 80000,
    image: "img/ikan teri.jpeg",
    description: "Harganya 80.000/kg. Disini jual berbagai macam macam ikan kering yaitu ikan Baung, ikan Batu, ikan Putih",
    stock: "Tersedia",
    labels: ["Ikan Lokal"],
    whatsapp: "6281337020531",
    featured: true
  },
  {
    id: 17,
    name: "Ayam Kampung",
    category: "Daging",
    store: "Lapak Dominggus",
    price: 50000,
    image: "img/ayam.jpeg",
    description: "Harganya ayam kecil 50.000, ayam sedang 100.000, ayam besar 150.000. Ayam berkualitas dengan daging padat dan rasa gurih alami, kaya protein",
    stock: "Tersedia",
    labels: ["Ayam Lokal"],
    whatsapp: "6285338370228",
    featured: true
  },
  {
    id: 18,
    name: "Sarung",
    category: "Produk Budaya",
    store: "Galeri Cinta kasih",
    price: 800000,
    image: "img/sarung.jpeg",
    description: "Harganya 800.000/lembar. Sarung tenun tradisional dengan motif khas yang unik dan elegan, dibuat dari bahan berkualitas dan cocok untuk acara adat, koleksi",
    stock: "Tersedia",
    labels: ["Produk Lokal"],
    whatsapp: "6281237584633",
    featured: true
  },
  {
    id: 19,
    name: "Parang",
    category: "Produk Budaya",
    store: "Lapak Dominggus",
    price: 1000000,
    image: "img/parang.jpeg",
    description: "Harganya 100.000/Batang. Kerajinan khas dengan desain unik dan nilai budaya yang tinggi, cocok sebagai pelengkap busana adat, koleksi",
    stock: "Tersedia",
    labels: ["Produk Lokal"],
    whatsapp: "6285338370228",
    featured: true
  },
  {
    id: 20,
    name: "Pinang",
    category: "Produk Budaya",
    store: "Lapak Mama Andre",
    price: 70000,
    image: "img/pinang.jpeg",
    description: "Harganya 70.000/kg, Buah pinang berkualitas dengan rasa dan aroma khas, cocok untuk kebutuhan tradisi, budaya, dan konsumsi sehari-hari. ",
    stock: "Tersedia",
    labels: ["Produk Lokal"],
    whatsapp: "6281237084654",
    featured: true
  },
  {
    id: 21,
    name: "Siri",
    category: "Produk Budaya",
    store: "Lapak Mama Andre",
    price: 20000,
    image: "img/sirih.jpeg",
    description: "Harganya 20.000/ikat, Buah pilihan dengan aroma khas dan kualitas terbaik, cocok untuk kebutuhan tradisi dan budaya. Segar, alami, dan bernilai budaya. ",
    stock: "Tersedia",
    labels: ["Produk Lokal"],
    whatsapp: "6281237084654",
    featured: true
  },
  {
    id: 22,
    name: "Rompi Motif",
    category: "Produk Budaya",
    store: "Galeri Cinta Kasih",
    price: 200000,
    image: "img/rompi.jpeg",
    description: "Harganya 200.000/lembar, Rompi khas Sumba yang nyaman, elegan, dan bermotif tradisional unik. ",
    stock: "Tersedia",
    labels: ["Produk Lokal"],
    whatsapp: "6281237584633",
    featured: true
  },
  {
    id: 23,
    name: "Kue Pisang",
    category: "Makanan",
    store: "Lapak Mama Rama",
    price: 1000,
    image: "img/pisang.jpeg",
    description: "Harganya 1.000/buah, Rompi khas Sumba yang nyaman, elegan, dan bermotif tradisional unik. ",
    stock: "Tersedia",
    labels: ["Makanan lezat"],
    whatsapp: "6281237584633",
    featured: true
  },
  {
    id: 24,
    name: "Bakso",
    category: "Makanan",
    store: "Lapak Ibu Marsela",
    price: 15000,
    image: "img/bakso.jpeg",
    description: "Harganya 15.000/mangkok, Olahan daging berkualitas dengan tekstur kenyal dan rasa gurih yang lezat, cocok dinikmati sebagai hidangan favorit keluarga. ",
    stock: "Tersedia",
    labels: ["Makanan lezat"],
    whatsapp: "6282136515706",
    featured: true
  },
  {
    id: 25,
    name: "Kue Molen",
    category: "Makanan",
    store: "Lapak Bapak Paulus",
    price: 1000,
    image: "img/molen.jpeg",
    description: "Harganya 1.000/buah, Camilan renyah dengan isian pisang manis yang lezat, cocok untuk teman santai kapan saja.",
    stock: "Tersedia",
    labels: ["Makanan lezat"],
    whatsapp: "6282136515706",
    featured: true
  },
  {
    id: 26,
    name: "Kue Cucur",
    category: "Makanan",
    store: "Lapak Mama Rama",
    price: 1000,
    image: "img/cucur.jpeg",
    description: "Harganya 1.000/buah, Kue tradisional manis dengan tekstur lembut dan renyah.",
    stock: "Tersedia",
    labels: ["Makanan lezat"],
    whatsapp: "6281237584633",
    featured: true
  },
  {
    id: 27,
    name: "Celana Cowok",
    category: "Aksesoris & Pakaian",
    store: "Toko Arafa",
    price: 80000,
    image: "img/celana.jpeg",
    description: "Harga celana pendek 30.000-80.000an, celana panjang 150.000-200.000an, Celana nyaman dan stylish, cocok untuk aktivitas sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "6282155000417",
    featured: true
  },
  {
    id: 28,
    name: "Kaos",
    category: "Aksesoris & Pakaian",
    store: "Toko Arafa",
    price: 50000,
    image: "img/baju.jpeg",
    description: "Harganya 50.000, pakaian nyaman dan simpel, cocok untuk digunakan sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "6282155000417",
    featured: true
  },
   {
    id: 29,
    name: "Sepatu",
    category: "Aksesoris & Pakaian",
    store: "Toko Arafa",
    price: 200000,
    image: "img/sepatu.jpeg",
    description: "Harganya 200.000, alas kaki nyaman dan stylish, cocok untuk berbagai aktivitas sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "6282155000417",
    featured: true
  },
   {
    id: 30,
    name: "Sendal",
    category: "Aksesoris & Pakaian",
    store: "Toko Arafa",
    price: 50000,
    image: "img/sendal.jpeg",
    description: "Harganya 50.000, alas kaki nyaman dan stylish, cocok untuk berbagai aktivitas sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "6282155000417",
    featured: true
  },
   {
    id: 31,
    name: "Jedai",
    category: "Aksesoris & Pakaian",
    store: "Lapak Delon",
    price: 5000,
    image: "img/jepit.jpeg",
    description: "Harganya 5.000-10.000an, jepit rambut praktis dan nyaman, cocok untuk berbagai gaya sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "6282247484070",
    featured: true
  },
   {
    id: 32,
    name: "Tas",
    category: "Aksesoris & Pakaian",
    store: "Toko Arafa",
    price: 100000,
    image: "img/tas.jpeg",
    description: "Harganya 100.000-200.000an, tas praktis dan stylish, cocok untuk menemani aktivitas sehari-hari.",
    stock: "Tersedia",
    labels: ["Bahan halus dan lembut"],
    whatsapp: "628215500041",
    featured: true
  },
   {
    id: 33,
    name: "Kartu",
    category: "Aksesoris Handphone",
    store: "Konter Galaxy Junior",
    price: 35000,
    image: "img/kartu.jpeg",
    description: "Harga kartu simpati 35.000, kartu by.u,kartu smartfren, kartu SIM dengan pilihan paket yang praktis untuk kebutuhan komunikasi dan internet sehari-hari.",
    stock: "Tersedia",
    labels: ["Bagus dan awet"],
    whatsapp: "6285321395361",
    featured: true
  },
   {
    id: 34,
    name: "Charger",
    category: "Aksesoris Handphone",
    store: "Konter Galaxy Junior",
    price: 80000,
    image: "img/charger.jpeg",
    description: "Harganya 80.000, Pengisi daya praktis dan andal untuk menjaga baterai ponsel tetap terisi kapan saja.",
    stock: "Tersedia",
    labels: ["Bagus dan awet"],
    whatsapp: "6285321395361",
    featured: true
  },
   {
    id: 35,
    name: "Case Hp",
    category: "Aksesoris Handphone",
    store: "Konter Galaxy Junior",
    price: 35000,
    image: "img/kesing.jpeg",
    description: "Harganya 35.000-40.000an, Pelindung ponsel yang stylish dan kokoh untuk menjaga perangkat tetap aman dari goresan dan benturan.",
    stock: "Tersedia",
    labels: ["Bagus dan awet"],
    whatsapp: "6285321395361",
    featured: true
  },
    {
    id: 36,
    name: "Anti Gores Hp",
    category: "Aksesoris Handphone",
    store: "Konter Galaxy Junior",
    price: 30000,
    image: "img/gores.jpeg",
    description: "Harganya 30.000, Pelindung layar yang menjaga ponsel dari goresan dan membantu mempertahankan kejernihan layar.",
    stock: "Tersedia",
    labels: ["Bagus dan awet"],
    whatsapp: "6285321395361",
    featured: true
  },
    {
    id: 37,
    name: "LCD Hp",
    category: "Aksesoris Handphone",
    store: "Konter Galaxy Junior",
    price: 180000,
    image: "img/lcd.jpeg",
    description: "Harganya 180.000, ",
    stock: "Tersedia",
    labels: ["Bagus dan awet"],
    whatsapp: "6285321395361",
    featured: true
  },
];


const shops = [
  {
    name: "Lapak febriano",
    category: "Sayur-sayuran",
    description: "Menjual sayur-sayuran yang segar & fresh.",
    open: "08.00 sampai 17.00",
    whatsapp: "6282210854706",
    
  },
  {
    name: "Kopi Matawai Jaya",
    category: "Kopi lokal",
    description: "Menyediakan kopi robusta dan arabika lokal dalam kemasan oleh-oleh.",
    open: "08.00 sampai 18.00",
    whatsapp: "6281234567890",
   
  },
  {
    name: "Warung Oleh-oleh Matawai",
    category: "Makanan lokal",
    description: "Menjual keripik, kue kering, sambal, dan camilan khas pasar.",
    open: "07.30 sampai 17.00",
    whatsapp: "6281234567890",
    
  },
  {
    name: "Rumah Kreatif Matawai",
    category: "Kerajinan dan aksesori",
    description: "Menjual tas tenun, anyaman, dan produk handmade dari pelaku usaha lokal.",
    open: "09.00 sampai 17.00",
    whatsapp: "6281234567890",
    
  }
];
